package com.allblue.model;

public class BlueUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_user.id
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_user.username
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_user.email
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_user.password
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_user.id
     *
     * @return the value of blue_user.id
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_user.id
     *
     * @param id the value for blue_user.id
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_user.username
     *
     * @return the value of blue_user.username
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_user.username
     *
     * @param username the value for blue_user.username
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_user.email
     *
     * @return the value of blue_user.email
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_user.email
     *
     * @param email the value for blue_user.email
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_user.password
     *
     * @return the value of blue_user.password
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_user.password
     *
     * @param password the value for blue_user.password
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}