package com.allblue.model;

public class BlueCustomer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_customer.id
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_customer.customer_name
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_customer.mobile
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_customer.password
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_customer.sex
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    private Boolean sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_customer.effective
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    private Boolean effective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_customer.region
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    private Boolean region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_customer.bank_card
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    private String bankCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_customer.idcard_num
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    private String idcardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_customer.remark
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_customer.deleted_at
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    private Integer deletedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_customer.belong_user_id
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    private Integer belongUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_customer.group_id
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    private Integer groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_customer.id
     *
     * @return the value of blue_customer.id
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_customer.id
     *
     * @param id the value for blue_customer.id
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_customer.customer_name
     *
     * @return the value of blue_customer.customer_name
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_customer.customer_name
     *
     * @param customerName the value for blue_customer.customer_name
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_customer.mobile
     *
     * @return the value of blue_customer.mobile
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_customer.mobile
     *
     * @param mobile the value for blue_customer.mobile
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_customer.password
     *
     * @return the value of blue_customer.password
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_customer.password
     *
     * @param password the value for blue_customer.password
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_customer.sex
     *
     * @return the value of blue_customer.sex
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_customer.sex
     *
     * @param sex the value for blue_customer.sex
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_customer.effective
     *
     * @return the value of blue_customer.effective
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public Boolean getEffective() {
        return effective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_customer.effective
     *
     * @param effective the value for blue_customer.effective
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public void setEffective(Boolean effective) {
        this.effective = effective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_customer.region
     *
     * @return the value of blue_customer.region
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public Boolean getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_customer.region
     *
     * @param region the value for blue_customer.region
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public void setRegion(Boolean region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_customer.bank_card
     *
     * @return the value of blue_customer.bank_card
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public String getBankCard() {
        return bankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_customer.bank_card
     *
     * @param bankCard the value for blue_customer.bank_card
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public void setBankCard(String bankCard) {
        this.bankCard = bankCard == null ? null : bankCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_customer.idcard_num
     *
     * @return the value of blue_customer.idcard_num
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public String getIdcardNum() {
        return idcardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_customer.idcard_num
     *
     * @param idcardNum the value for blue_customer.idcard_num
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public void setIdcardNum(String idcardNum) {
        this.idcardNum = idcardNum == null ? null : idcardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_customer.remark
     *
     * @return the value of blue_customer.remark
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_customer.remark
     *
     * @param remark the value for blue_customer.remark
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_customer.deleted_at
     *
     * @return the value of blue_customer.deleted_at
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public Integer getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_customer.deleted_at
     *
     * @param deletedAt the value for blue_customer.deleted_at
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public void setDeletedAt(Integer deletedAt) {
        this.deletedAt = deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_customer.belong_user_id
     *
     * @return the value of blue_customer.belong_user_id
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public Integer getBelongUserId() {
        return belongUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_customer.belong_user_id
     *
     * @param belongUserId the value for blue_customer.belong_user_id
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public void setBelongUserId(Integer belongUserId) {
        this.belongUserId = belongUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_customer.group_id
     *
     * @return the value of blue_customer.group_id
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_customer.group_id
     *
     * @param groupId the value for blue_customer.group_id
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}