package com.allblue.model;

public class BlueGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_group.id
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_group.name
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_group.id
     *
     * @return the value of blue_group.id
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_group.id
     *
     * @param id the value for blue_group.id
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_group.name
     *
     * @return the value of blue_group.name
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_group.name
     *
     * @param name the value for blue_group.name
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}