package com.allblue.mapper;

import com.allblue.model.BlueCustomer;
import com.allblue.model.BlueCustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlueCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_customer
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int countByExample(BlueCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_customer
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int deleteByExample(BlueCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_customer
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_customer
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int insert(BlueCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_customer
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int insertSelective(BlueCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_customer
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    List<BlueCustomer> selectByExample(BlueCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_customer
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    BlueCustomer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_customer
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") BlueCustomer record, @Param("example") BlueCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_customer
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int updateByExample(@Param("record") BlueCustomer record, @Param("example") BlueCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_customer
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int updateByPrimaryKeySelective(BlueCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_customer
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int updateByPrimaryKey(BlueCustomer record);
}