package com.allblue.mapper;

import com.allblue.model.BlueUser;
import com.allblue.model.BlueUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface BlueUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_user
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int countByExample(BlueUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_user
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int deleteByExample(BlueUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_user
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_user
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int insert(BlueUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_user
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int insertSelective(BlueUser record);

    /**
    * @Description:根据用户名和密码查询用户ID
    * @Author Xone
    * @Date 19:03 2018/7/22
    **/
    int selectByUserInfo(BlueUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_user
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    List<BlueUser> selectByExample(BlueUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_user
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    BlueUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_user
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") BlueUser record, @Param("example") BlueUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_user
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int updateByExample(@Param("record") BlueUser record, @Param("example") BlueUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_user
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int updateByPrimaryKeySelective(BlueUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_user
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int updateByPrimaryKey(BlueUser record);
}