package com.allblue.mapper;

import com.allblue.model.BlueGroup;

public interface BlueGroupMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_group
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_group
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int insert(BlueGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_group
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int insertSelective(BlueGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_group
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    BlueGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_group
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int updateByPrimaryKeySelective(BlueGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_group
     *
     * @mbggenerated Thu Jul 19 18:13:59 CST 2018
     */
    int updateByPrimaryKey(BlueGroup record);
}